# -*- coding: utf-8 -*-
"""crime_dash.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PiUqGDN1tPL5LXbRp2xf2Df1vkCIJvBn
"""

import streamlit as st

# Title for the app
st.title("Criminal & Non-Criminal Reports")

# Embed Power BI dashboard
power_bi_url = "https://app.powerbi.com/reportEmbed?reportId=d1b1b121-8ea3-45d9-876f-99d4287416b4&autoAuth=true&ctid=84a28940-b464-41c3-ba3b-b4fa6665bc05"  # Replace with your Power BI embed URL

# Render the Power BI dashboard using an iframe
st.markdown(
    f"""
    <iframe title="Crime Reporting - BI" width="1000" height="541.25" src="https://app.powerbi.com/reportEmbed?reportId=d1b1b121-8ea3-45d9-876f-99d4287416b4&autoAuth=true&ctid=84a28940-b464-41c3-ba3b-b4fa6665bc05" frameborder="0" allowFullScreen="true"></iframe>
    """,
    unsafe_allow_html=True,
)